### ISSUE TITLE
Consider Schema Changes

### ISSUE THREAD

**Issue by nodh** [ehn-dcc-development/hcert-kotlin#16]
Consider relevant changes to the schema: https://github.com/ehn-dcc-development/ehn-dcc-schema/releases

**Comment by alexKatona** [comment]
Its basically only making the test facility nullable right ? Since the DOB is already in string and Can be empty

**Comment by JesusMcCloud** [comment]
89a5ce35624562978b38172ee4899540278a3d53 partially addresses this by differentiating between version 1.3.0 and earlier versions.
However, it still needs improvement:
 * add all schema versions and handle the accordingly
 * handle unknown schema versions
 * add the ability to augment data parsing in order to handle structural changes for different schema versions
 * thoroughly test against 1.3.0
