### ISSUE TITLE
Question: Publishing

### ISSUE THREAD

**Issue by Alival-IT** [ehn-dcc-development/hcert-kotlin#3]
Hello there,

I would like to ask you if you are planning to publish the library to a public repository so I dont have to create a github access token to get it. The main reason is becasue I am thinking about using this library in our green pass applications and it seems like the most effective way is to have one good library shared across countries rather than having custom implementations.

**Comment by nodh** [comment]
At this moment, we don't have any intention to publish the library itself on lets say Maven Central. But feel free to fork this library and publish it internally. That way, you can also deal with upcoming, possibly breaking changes more easily (and there will be changes).

**Comment by asitplus-pteufl** [comment]
hi, I agree, but well that's more a questions of resources and time. we are in the progress to get the qr-creation and validation running for austria. it has been decided that the relevant code will be published as OSS (apache2) and we will also update this code here (for sure there are still errors/problems) but currently we cannot do more due to constrained time/resources.

**Comment by jnischler** [comment]
hey, we were also facing the same problem.
We created a fork and did some small modifications to allow building using jitpack.
Our fork:
https://github.com/section42/hcert-kotlin
jitpack test release:
https://jitpack.io/#section42/hcert-kotlin/1.0.3-jitpacktest

Be AWARE this is not the official library, and we maybe need to make some modifications.
We can make a PR to allow the official library to use jitpack, only minor modifications are required.

Maybe this will help regards.
Julian
