### ISSUE TITLE
Missing hcert-kotlin.js

### ISSUE THREAD

**Issue by zeroninjahack** [ehn-dcc-development/hcert-kotlin#66]
Hi, 

i can't find hcert-kotlin.js path and a file. There is no path like this: build/distributions/hcert-kotlin.js. My demo.html file also can't load js data, because there is no javascript file.

**Comment by nodh** [comment]
As mentioned in the Readme: https://github.com/ehn-dcc-development/hcert-kotlin#usage-js
Build the module either for development or production:
```
./gradlew jsBrowserDevelopmentWebpack
./gradlew jsBrowserProductionWebpack
```

**Comment by jumpjack** [comment]
Seriously, why don't you include the core of your library in your repo?!?

**Comment by JesusMcCloud** [comment]
> Seriously, why don't you include the core of your library in your repo?!?
We may have a misunderstanding here.

This is a ***Kotlin*** multiplatform project. Hence, *there are no JavaScript sources*, only compiler output targeting JS (browser or NodeJS; see readme) and the JVM, All the sources and everything required to build a working JS and JVM lib are there and build instructions are documented (see previous comment). Consequently, the core, all testcases, test data, etc is present and placed according to the usual conventions.

If you're having trouble building any of the targets, or if the readme is unclear or misleading, please elaborate. We're happy to receive feedback. Our intent has always been to make this project accessible and to have work well on different targets.

**Comment by jumpjack** [comment]
I am looking for a COSE pure javascript library ready for use, so this repo is not for me.

**Comment by JesusMcCloud** [comment]
Feel free to look through our JS dependencies for pointers. We use the excellent [cose-js](https://github.com/erdtman/cose-js), btw and recently upstreamed a contribution such that it fulfils all requirements for handling the EU's DCCs.
Just to be clear: this repo contains a full-blown multiplatform implementation for creating and verifying DCCs in the browser and on JVM targets including Android. It is fully usable in the browser, since it produces pure JavaScript without any NodeJS dependencies by default.

Good luck!
